
# name of the source json file containing parameter definitions
params_file: 'params.json'

######################################################################
# parameter table

## name of the target LaTeX file containing the parameter table
params_table_tex_file: 'parameter_table.tex' 

## definition of table columns: parameter fields and column titles
## (note: multiple fields can be printed in the same column (e.g., value and unit) using lists of fields)
params_table_columns:
- field: name
  title: Name
- field: [value, unit]
  title: Value
- field: docstring
  title: Description

## relative column widths
params_table_column_widths: [1,2,4]

## select sections and section titles to be printed in table, and text color, and
## background color of section titles.
## note: title, color and title_color are optional. If not defined, default values
## will be used: title=None (no title printed), color=black, and title_color=lightgray
params_table_sections:
- section: network
  title: Network
  color: black
  title_color: lightgray
- section: network_drvd
  color: gray
- section: connectivity
  title: Connectivity
  color: black
  title_color: lightgray
- section: connectivity_drvd
  color: gray
- section: neuron
  title: Neuron
  color: black
  title_color: lightgray
- section: synapse
  title: Synapse
  color: black
  title_color: lightgray
- section: synapse_drvd
  color: gray
- section: input
  title: Input
  color: black
  title_color: lightgray
- section: simulation
  title: Simulation
  color: black
  title_color: lightgray
  
######################################################################
# LaTeX macros

## name of the target LaTeX file containing macro definitions
macros_tex_file: 'macros.tex'

## prefix for LaTeX macros (can be used to avoid collisions with LaTeX commands)
## (example: parameter "gamma" will be turned into macro "\Pgamma" if prefix is 'P')
macros_prefix: 'P'

## name of the target LaTeX file containing macro table
macros_table_tex_file: 'macros_table.tex'

## definition of table columns: parameter fields and column titles
macros_table_columns:
- field: name
  title: Parameter name
- field: key
  title: Macro name
- field: docstring
  title: Description

## relative column widths
macros_table_column_widths: [2,2,4]

## select sections and section titles to be printed in table, and text color, and
## background color of section titles.
## note: title, color and title_color are optional. If not defined, default values
## will be used: title=None (no title printed), color=black, and title_color=lightgray
macros_table_sections:
- section: network
  title: Network
  color: black
  title_color: lightgray
- section: network_drvd
  color: gray
  title_color:  
- section: connectivity
  title: Connectivity
  color: black
  title_color: lightgray
- section: connectivity_drvd
  color: gray
- section: neuron
  title: Neuron
  color: black
  title_color: lightgray
- section: synapse
  title: Synapse
  color: black
  title_color: lightgray
- section: synapse_drvd
  color: gray
- section: input
  title: Input
  color: black
  title_color: lightgray
- section: simulation
  title: Simulation
  color: black
  title_color: lightgray
  