
# name of the source json file containing parameter definitions
params_file: 'params.json'

######################################################################
# parameter table

## name of the target LaTeX file containing the parameter table
params_table_tex_file: 'parameter_table.tex' 

## definition of table columns: parameter fields and column titles
## (note: multiple fields can be printed in the same column (e.g., value and unit) using lists of fields)
params_table_columns:
- field: name
  title: Name
- field: [value, unit]
  title: Value
- field: docstring
  title: Description

## relative column widths
params_table_column_widths: [1,1,4]

## select sections and section titles to be printed in table, and text color
## (note: empty titles will not be printed)
params_table_sections:
- section: network
  title: Network
  color: black
- section: network_drvd
  title: 
  color: gray
- section: connectivity
  title: Connectivity
  color: black
- section: neuron
  title: Neuron
  color: black  
- section: synapse
  title: Synapse
  color: black
- section: synapse_drvd
  title: 
  color: gray
- section: simulation
  title: Simulation
  color: black

######################################################################
# LaTeX macros

## name of the target LaTeX file containing macro definitions
macros_tex_file: 'macros.tex'

## prefix for LaTeX macros (can be used to avoid collisions with LaTeX commands)
## (example: parameter "gamma" will be turned into macro "\Pgamma" if prefix is 'P')
macros_prefix: 'P'

## name of the target LaTeX file containing macro table
macros_table_tex_file: 'macros_table.tex'

## definition of table columns: parameter fields and column titles
macros_table_columns:
- field: name
  title: Parameter name
- field: key
  title: Macro name
- field: docstring
  title: Description

## relative column widths
macros_table_column_widths: [2,2,4]

## select sections and section titles to be printed in table, and text color
macros_table_sections:
- section: network
  title: 
  color: black
- section: network_drvd
  title: 
  color: gray
- section: connectivity
  title: 
  color: black
- section: neuron
  title: 
  color: black  
- section: synapse
  title: 
  color: black
- section: synapse_drvd
  title: 
  color: gray
- section: simulation
  title: 
  color: black