
## name of the target LaTeX file containing the parameter table
params_tex_file: 'macros_table.tex' 

## definition of table columns: parameter fields and column titles
##  note: multiple fields can be printed in the same column (e.g., value and unit) using lists of fields
table_columns:
- field: name
  title: Name
- field: key
  title: Macro
- field: docstring
  title: Description

## relative column widths
table_column_widths: [1,1,4]

## select sections and section titles to be printed in table, and text color
##   note: empty titles will not be printed
table_sections:
- section: network
  title: 
  color: black
- section: network_drvd
  title: 
  color: gray
- section: connectivity
  title: 
  color: black
- section: neuron
  title: 
  color: black  
- section: synapse
  title: 
  color: black
- section: synapse_drvd
  title: 
  color: gray
- section: simulation
  title: 
  color: black

## name of the target LaTeX file containing macro definitions
macros_tex_file: 'macros.tex' 
